# Generated by Django 4.0.4 on 2022-04-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='media')),
                ('title', models.TextField()),
                ('rank', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='slider',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
